/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.68
 * Generated at: 2022-11-07 08:38:07 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class deleteuser_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/layout/header.jsp", Long.valueOf(1667749027791L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("  <title>TravelPlan</title>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css\">\r\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/npm/jquery@3.6.0/dist/jquery.slim.min.js\"></script>\r\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\"></script>\r\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-expand-md bg-dark navbar-dark\">\r\n");
      out.write("  <a class=\"navbar-brand\" href=\"#\">TravelPlan</a>\r\n");
      out.write("  <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#collapsibleNavbar\">\r\n");
      out.write("    <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("  </button>\r\n");
      out.write("  <div class=\"collapse navbar-collapse\" id=\"collapsibleNavbar\">\r\n");
      out.write("    <ul class=\"navbar-nav\">\r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("        <a class=\"nav-link\" href=\"#\">회원가입</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("        <a class=\"nav-link\" href=\"/login\">로그인</a>\r\n");
      out.write("      </li>\r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("        <a class=\"nav-link\" href=\"/mypage\">마이페이지</a>\r\n");
      out.write("      </li>  \r\n");
      out.write("      <li class=\"nav-item\">\r\n");
      out.write("        <a class=\"nav-link\" href=\"#\">게시판</a>\r\n");
      out.write("      </li>    \r\n");
      out.write("    </ul>\r\n");
      out.write("  </div>  \r\n");
      out.write("</nav>\r\n");
      out.write("<br>\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("	<meta charset=\"UTF-8\">\r\n");
      out.write("	<style>\r\n");
      out.write("		* {\r\n");
      out.write("			margin: 0;\r\n");
      out.write("			padding: 0;\r\n");
      out.write("		}\r\n");
      out.write("		#wrap {\r\n");
      out.write("			width: auto;\r\n");
      out.write("			min-width: 1560px;\r\n");
      out.write("			max-width: 1880px;\r\n");
      out.write("			padding: 0px 40px;\r\n");
      out.write("			margin: 0px auto;\r\n");
      out.write("			box-sizing: border-box;\r\n");
      out.write("		}\r\n");
      out.write("		#sub_header {\r\n");
      out.write("			position: relative;\r\n");
      out.write("			padding: 0px 0px 10px;\r\n");
      out.write("			margin: 0px auto;\r\n");
      out.write("		}\r\n");
      out.write("		.visual_area {\r\n");
      out.write("			padding: 5px 0px 8px;\r\n");
      out.write("			font-size: inherit;\r\n");
      out.write("			font-weight: normal;\r\n");
      out.write("		}\r\n");
      out.write("		.txt > a {\r\n");
      out.write("			display: inline-block;\r\n");
      out.write("			font-size: 30px;\r\n");
      out.write("			font-weight: normal;\r\n");
      out.write("			color: rgb(0, 0, 0);\r\n");
      out.write("		}\r\n");
      out.write("		.menu_area {\r\n");
      out.write("			float : left;\r\n");
      out.write("			width : 270px;\r\n");
      out.write("			border-right: 1px solid #ddd;\r\n");
      out.write("		}\r\n");
      out.write("		.content_right {\r\n");
      out.write("			position: absolute;\r\n");
      out.write("			left: 270px;\r\n");
      out.write("			top: 200;\r\n");
      out.write("			right: 0;\r\n");
      out.write("			min-width: 1229px;\r\n");
      out.write("		}\r\n");
      out.write("		.menu_area { \r\n");
      out.write("		 	width: 170px;\r\n");
      out.write("		 	float: left;\r\n");
      out.write("		 	margin: 24px 40px 0px 0px;\r\n");
      out.write("		 	font-size: 14px;\r\n");
      out.write("		}\r\n");
      out.write("		.menu1, .menu2 {\r\n");
      out.write("			display: flex;\r\n");
      out.write("			flex-direction: column;\r\n");
      out.write("			padding-bottom: 15px;\r\n");
      out.write("		}\r\n");
      out.write("		.update, .delete, .post, .comment {\r\n");
      out.write("			display: flex;\r\n");
      out.write("			margin-top: 2px;\r\n");
      out.write("			font-size: 16px;\r\n");
      out.write("			line-height: 30px;\r\n");
      out.write("			color: rgb(110, 110, 110);\r\n");
      out.write("		}\r\n");
      out.write("		.content-right {\r\n");
      out.write("			padding: 0;\r\n");
      out.write("			float: right;\r\n");
      out.write("		}\r\n");
      out.write("		.sectiontitle {\r\n");
      out.write("			border-bottom: 2px solid #000000;\r\n");
      out.write("			padding-left: 10px;\r\n");
      out.write("			padding-bottom: 14px;\r\n");
      out.write("			margin-top: 22px;\r\n");
      out.write("			line-height: 1.5px;\r\n");
      out.write("			font-size: 14px;\r\n");
      out.write("			position: relative;\r\n");
      out.write("		}\r\n");
      out.write("		.password {\r\n");
      out.write("			padding: 3px 0 35px 0;\r\n");
      out.write("		}\r\n");
      out.write("		.inputpwd {\r\n");
      out.write("			margin-top: 22px;\r\n");
      out.write("			padding: 10px;\r\n");
      out.write("			font-size: 15px;\r\n");
      out.write("			border-collapse: collapse;\r\n");
      out.write("			table-layout: fixed;\r\n");
      out.write("			margin-left: 20%;\r\n");
      out.write("		}\r\n");
      out.write("		tr {\r\n");
      out.write("			height: 70px;\r\n");
      out.write("			padding: 10px;\r\n");
      out.write("			box-sizing: border-box;\r\n");
      out.write("			text-align: center;\r\n");
      out.write("			vertical-align: middle;\r\n");
      out.write("			word-break: break-all;\r\n");
      out.write("		}\r\n");
      out.write("		.button {\r\n");
      out.write("			margin-left: 30%;\r\n");
      out.write("		}\r\n");
      out.write("		.btn_delete {\r\n");
      out.write("			width: 200px;\r\n");
      out.write("			height: 50px;\r\n");
      out.write("			font-size: 15px;\r\n");
      out.write("			border-collapse: collapse;\r\n");
      out.write("			vertical-align: middle;\r\n");
      out.write("			color: rgb(255, 255, 255);\r\n");
      out.write("			background-color: rgb(50, 50, 50);\r\n");
      out.write("		}\r\n");
      out.write("	</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div id=\"wrap\">\r\n");
      out.write("		<div id =\"header\">\r\n");
      out.write("			<div class=\"visual_area\">\r\n");
      out.write("				<h1 class=\"txt\">\r\n");
      out.write("					<a href=\"/mypage\">My Page</a>\r\n");
      out.write("				</h1>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div id =\"content_area\">\r\n");
      out.write("			<div class =\"content\">\r\n");
      out.write("				<div class=\"content_in\">\r\n");
      out.write("					<!-- 좌측 메뉴 -->\r\n");
      out.write("					<nav class=\"menu_area\">\r\n");
      out.write("						<div class=\"menu1\">\r\n");
      out.write("							<h5>개인정보관리</h5>\r\n");
      out.write("							<a href=\"/mypage\" class=\"update\">회원정보수정</a>\r\n");
      out.write("							<a href=\"/deleteuser\" class=\"delete\">회원탈퇴</a>\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"menu2\">\r\n");
      out.write("							<h5>게시판</h5>\r\n");
      out.write("							<a href=\"#\" class=\"post\">내가 쓴 글</a>\r\n");
      out.write("							<a href=\"#\" class=\"comment\">내가 쓴 댓글</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</nav>\r\n");
      out.write("					<!-- 콘텐츠 내용 -->\r\n");
      out.write("					<section class =\"content_right\">\r\n");
      out.write("						<header class=\"sectiontitle\">\r\n");
      out.write("							<h5>회원탈퇴</h5>\r\n");
      out.write("						</header>\r\n");
      out.write("						<form action=\"/deleteuser\" method=\"post\">\r\n");
      out.write("							<div class=\"password\">\r\n");
      out.write("								<table class=\"inputpwd\">\r\n");
      out.write("									<tr>\r\n");
      out.write("										<td width=180px><label for=\"myPwd\">비밀번호</label></td>\r\n");
      out.write("										<td><input type=\"password\" name=\"pwd\" placeholder=\"비밀번호\" size=20/></td>\r\n");
      out.write("									</tr>\r\n");
      out.write("									<tr>\r\n");
      out.write("										<td><label for=\"PwdR\">비밀번호 확인</label></td>\r\n");
      out.write("										<td><input type=\"password\" name=\"pwdr\" placeholder=\"비밀번호 확인\" size=20/></td>\r\n");
      out.write("									</tr>\r\n");
      out.write("								</table>\r\n");
      out.write("							</div>	\r\n");
      out.write("							<div class=\"button\">\r\n");
      out.write("								<button type=\"submit\" class=\"btn_delete\">탈퇴</button>\r\n");
      out.write("							</div>	\r\n");
      out.write("						</form>\r\n");
      out.write("					</section>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
